entrypoint: "gunicorn -b :$PORT main:app"
env: flex
runtime: python
runtime_config: 
  python_version: 3

env_variables:
  CLOUD_SQL_USERNAME: Bryan
  CLOUD_SQL_PASSWORD: 123
  CLOUD_SQL_DATABASE_NAME: songsdb
  CLOUD_SQL_CONNECTION_NAME: psychic-bedrock-329522:us-central1:flaskdemomysql
